import React, { useState } from 'react';
import { 
  FileEdit, 
  Plus, 
  Save, 
  Download, 
  Trash2, 
  FileText,
  Copy,
  BookOpen,
  CheckCircle,
  Clock,
  Edit3,
  Eye,
  Settings,
  ChevronRight,
  ChevronDown,
  AlignLeft,
  Bold,
  Italic,
  List,
  Image,
  Link,
  Table,
  Quote
} from 'lucide-react';
import { motion } from 'framer-motion';
import { useReportStore, useAppStore } from '@/stores';
import type { Report, ReportSection, Reference } from '@/types';

const ReportWriter: React.FC = () => {
  const [activeReport, setActiveReport] = useState<Report | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [activeSection, setActiveSection] = useState<string>('introduction');
  const [showTemplates, setShowTemplates] = useState(false);
  const [reportTitle, setReportTitle] = useState('');
  const [reportType, setReportType] = useState<Report['type']>('business');
  
  const { reports, addReport, updateReport, deleteReport } = useReportStore();
  const { addNotification } = useAppStore();

  const reportTypes = [
    { id: 'academic' as const, label: 'Academic', icon: BookOpen, color: 'from-blue-500 to-cyan-500' },
    { id: 'business' as const, label: 'Business', icon: FileText, color: 'from-green-500 to-emerald-500' },
    { id: 'technical' as const, label: 'Technical', icon: Settings, color: 'from-purple-500 to-pink-500' },
    { id: 'creative' as const, label: 'Creative', icon: Edit3, color: 'from-orange-500 to-amber-500' },
  ];

  const templates = [
    {
      id: 'standard',
      name: 'Standard Report',
      description: 'Traditional report structure with abstract, introduction, methods, results, and conclusion',
      sections: ['Abstract', 'Introduction', 'Literature Review', 'Methodology', 'Results', 'Discussion', 'Conclusion', 'References']
    },
    {
      id: 'business',
      name: 'Business Proposal',
      description: 'Professional business proposal format with executive summary and financial projections',
      sections: ['Executive Summary', 'Company Overview', 'Problem Statement', 'Solution', 'Market Analysis', 'Financial Projections', 'Timeline', 'Conclusion']
    },
    {
      id: 'technical',
      name: 'Technical Documentation',
      description: 'Detailed technical spec with architecture, implementation, and API documentation',
      sections: ['Overview', 'Requirements', 'Architecture', 'Design', 'Implementation', 'Testing', 'Deployment', 'Maintenance']
    },
  ];

  const createNewReport = (template?: typeof templates[0]) => {
    const sections = template?.sections.map((title, index) => ({
      id: Date.now().toString() + index,
      title,
      subsections: []
    })) || [
      { id: '1', title: 'Introduction', subsections: [] },
      { id: '2', title: 'Main Content', subsections: [] },
      { id: '3', title: 'Conclusion', subsections: [] },
    ];

    const newReport: Report = {
      id: Date.now().toString(),
      title: reportTitle || 'Untitled Report',
      type: reportType,
      outline: { sections },
      content: {
        introduction: '',
        chapters: [],
        conclusion: '',
        references: []
      },
      status: 'draft',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      wordCount: 0,
      format: 'pdf'
    };

    addReport(newReport);
    setActiveReport(newReport);
    setShowTemplates(false);
    setReportTitle('');
    addNotification('Report created successfully!', 'success');
  };

  const saveReport = () => {
    if (!activeReport) return;
    
    updateReport(activeReport.id, {
      ...activeReport,
      title: activeReport.title,
      updatedAt: new Date().toISOString()
    });
    
    addNotification('Report saved!', 'success');
  };

  const generateContent = () => {
    if (!activeReport) return;
    
    // Simulate AI content generation
    addNotification('Generating content with AI...', 'info');
    
    setTimeout(() => {
      updateReport(activeReport.id, {
        ...activeReport,
        content: {
          introduction: 'This is an auto-generated introduction section. The AI has analyzed your topic and created relevant content based on your research and specifications.',
          chapters: activeReport.outline.sections.slice(1, -1).map(section => ({
            id: section.id,
            title: section.title,
            sections: [{
              id: Date.now().toString(),
              title: 'Section Content',
              content: 'This is sample content generated by AI. In a real application, this would analyze your research data and create comprehensive content for each section based on the report type and topic.'
            }]
          })),
          conclusion: 'This is an auto-generated conclusion. The AI has synthesized the key points from your report and provided recommendations for next steps.',
          references: [
            { id: '1', authors: ['Author 1', 'Author 2'], title: 'Sample Reference 1', source: 'Journal Name', year: 2024, url: 'https://example.com' },
            { id: '2', authors: ['Author 3'], title: 'Sample Reference 2', source: 'Conference Proceedings', year: 2023, doi: '10.1000/example' }
          ]
        },
        wordCount: 2500,
        updatedAt: new Date().toISOString()
      });
      
      setActiveReport({
        ...activeReport,
        content: {
          introduction: 'This is an auto-generated introduction section. The AI has analyzed your topic and created relevant content based on your research and specifications.',
          chapters: activeReport.outline.sections.slice(1, -1).map(section => ({
            id: section.id,
            title: section.title,
            sections: [{
              id: Date.now().toString(),
              title: 'Section Content',
              content: 'This is sample content generated by AI. In a real application, this would analyze your research data and create comprehensive content for each section based on the report type and topic.'
            }]
          })),
          conclusion: 'This is an auto-generated conclusion. The AI has synthesized the key points from your report and provided recommendations for next steps.',
          references: [
            { id: '1', authors: ['Author 1', 'Author 2'], title: 'Sample Reference 1', source: 'Journal Name', year: 2024, url: 'https://example.com' },
            { id: '2', authors: ['Author 3'], title: 'Sample Reference 2', source: 'Conference Proceedings', year: 2023, doi: '10.1000/example' }
          ]
        },
        wordCount: 2500,
        updatedAt: new Date().toISOString()
      });
      
      addNotification('Content generated successfully!', 'success');
    }, 2000);
  };

  const getStatusColor = (status: Report['status']) => {
    switch (status) {
      case 'draft': return 'text-yellow-400 bg-yellow-400/20';
      case 'review': return 'text-blue-400 bg-blue-400/20';
      case 'final': return 'text-green-400 bg-green-400/20';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">Report Writer</h2>
          <p className="text-slate-400">Create professional reports with AI assistance</p>
        </div>
        <div className="flex gap-3">
          <button 
            onClick={() => setShowTemplates(true)}
            className="btn-secondary flex items-center gap-2"
          >
            <Plus className="w-5 h-5" />
            New Report
          </button>
        </div>
      </div>

      {/* Templates Modal */}
      {showTemplates && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          onClick={() => setShowTemplates(false)}
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-slate-800 rounded-2xl p-6 max-w-4xl w-full max-h-[80vh] overflow-y-auto"
            onClick={(e) => e.stopPropagation()}
          >
            <h3 className="text-xl font-semibold text-white mb-6">Create New Report</h3>
            
            {/* Report Type */}
            <div className="mb-6">
              <label className="text-sm text-slate-400 mb-3 block">Report Type</label>
              <div className="grid grid-cols-4 gap-4">
                {reportTypes.map((type) => (
                  <button
                    key={type.id}
                    onClick={() => setReportType(type.id)}
                    className={`p-4 rounded-xl border-2 transition-all ${
                      reportType === type.id
                        ? 'border-cyan-500 bg-cyan-500/10'
                        : 'border-slate-600 hover:border-slate-500'
                    }`}
                  >
                    <div className={`w-10 h-10 rounded-lg bg-gradient-to-br ${type.color} 
                                  flex items-center justify-center mx-auto mb-2`}>
                      <type.icon className="w-5 h-5 text-white" />
                    </div>
                    <p className="text-sm text-white">{type.label}</p>
                  </button>
                ))}
              </div>
            </div>

            {/* Report Title */}
            <div className="mb-6">
              <label className="text-sm text-slate-400 mb-2 block">Report Title</label>
              <input
                type="text"
                value={reportTitle}
                onChange={(e) => setReportTitle(e.target.value)}
                placeholder="Enter report title..."
                className="input-field"
              />
            </div>

            {/* Templates */}
            <div className="mb-6">
              <label className="text-sm text-slate-400 mb-3 block">Choose Template</label>
              <div className="grid grid-cols-3 gap-4">
                {templates.map((template) => (
                  <button
                    key={template.id}
                    onClick={() => createNewReport(template)}
                    className="p-4 rounded-xl border border-slate-600 hover:border-cyan-500 hover:bg-cyan-500/10 transition-all text-left"
                  >
                    <h4 className="text-white font-medium mb-2">{template.name}</h4>
                    <p className="text-xs text-slate-400 mb-3">{template.description}</p>
                    <div className="flex flex-wrap gap-1">
                      {template.sections.slice(0, 4).map((section) => (
                        <span key={section} className="px-2 py-0.5 rounded bg-slate-700 text-xs text-slate-300">
                          {section}
                        </span>
                      ))}
                      {template.sections.length > 4 && (
                        <span className="px-2 py-0.5 rounded bg-slate-700 text-xs text-slate-400">
                          +{template.sections.length - 4}
                        </span>
                      )}
                    </div>
                  </button>
                ))}
              </div>
            </div>

            <button
              onClick={() => createNewReport()}
              className="w-full btn-primary"
            >
              Create Blank Report
            </button>
          </motion.div>
        </motion.div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Reports List */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="lg:col-span-1 card"
        >
          <h3 className="text-lg font-semibold text-white mb-4">My Reports</h3>
          <div className="space-y-3">
            {reports.length === 0 ? (
              <p className="text-slate-400 text-sm text-center py-8">No reports yet</p>
            ) : (
              reports.map((report) => (
                <div
                  key={report.id}
                  onClick={() => setActiveReport(report)}
                  className={`p-4 rounded-xl cursor-pointer transition-all ${
                    activeReport?.id === report.id
                      ? 'bg-cyan-500/20 border border-cyan-500/50'
                      : 'bg-slate-700/30 hover:bg-slate-700/50'
                  }`}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1 min-w-0">
                      <h4 className="text-sm font-medium text-white truncate">{report.title}</h4>
                      <p className="text-xs text-slate-400 mt-1">
                        {report.wordCount.toLocaleString()} words
                      </p>
                    </div>
                    <span className={`px-2 py-0.5 rounded text-xs ${getStatusColor(report.status)}`}>
                      {report.status}
                    </span>
                  </div>
                </div>
              ))
            )}
          </div>
        </motion.div>

        {/* Editor */}
        <div className="lg:col-span-2 space-y-6">
          {activeReport ? (
            <>
              {/* Toolbar */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="card"
              >
                <div className="flex items-center justify-between mb-4">
                  <input
                    type="text"
                    value={activeReport.title}
                    onChange={(e) => setActiveReport({ ...activeReport, title: e.target.value })}
                    className="text-xl font-semibold bg-transparent border-none text-white focus:outline-none w-full"
                    placeholder="Report Title"
                  />
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => setIsEditing(!isEditing)}
                      className={`p-2 rounded-lg transition-colors ${
                        isEditing ? 'bg-cyan-500/20 text-cyan-400' : 'hover:bg-slate-700 text-slate-400'
                      }`}
                    >
                      {isEditing ? <Eye className="w-5 h-5" /> : <Edit3 className="w-5 h-5" />}
                    </button>
                    <button onClick={saveReport} className="p-2 rounded-lg hover:bg-slate-700 text-slate-400 hover:text-white transition-colors">
                      <Save className="w-5 h-5" />
                    </button>
                    <button className="p-2 rounded-lg hover:bg-slate-700 text-slate-400 hover:text-white transition-colors">
                      <Download className="w-5 h-5" />
                    </button>
                  </div>
                </div>

                {/* Formatting Toolbar */}
                <div className="flex items-center gap-2 p-2 bg-slate-700/30 rounded-lg">
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Bold className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Italic className="w-4 h-4" />
                  </button>
                  <div className="w-px h-6 bg-slate-600" />
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <List className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <AlignLeft className="w-4 h-4" />
                  </button>
                  <div className="w-px h-6 bg-slate-600" />
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Link className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Image className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Table className="w-4 h-4" />
                  </button>
                  <button className="p-2 rounded hover:bg-slate-600 text-slate-400 hover:text-white">
                    <Quote className="w-4 h-4" />
                  </button>
                </div>
              </motion.div>

              {/* Content */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 }}
                className="card min-h-96"
              >
                {isEditing ? (
                  <textarea
                    value={activeReport.content.introduction || ''}
                    onChange={(e) => setActiveReport({
...activeReport,
                      content: { ...activeReport.content, introduction: e.target.value }
                    })}
                    className="w-full h-full min-h-96 bg-transparent border-none text-white resize-none focus:outline-none"
                    placeholder="Start writing your report..."
                  />
                ) : (
                  <div className="prose prose-invert max-w-none">
                    {activeReport.content.introduction ? (
                      <div className="text-white whitespace-pre-wrap">
                        {activeReport.content.introduction}
                      </div>
                    ) : (
                      <p className="text-slate-500 italic">
                        Click edit to start writing, or generate content with AI
                      </p>
                    )}
                  </div>
                )}
              </motion.div>

              {/* AI Generate Button */}
              <motion.button
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                onClick={generateContent}
                className="w-full py-4 rounded-xl bg-gradient-to-r from-cyan-500 to-purple-600 text-white font-semibold
                          hover:from-cyan-600 hover:to-purple-700 transition-all shadow-lg hover:shadow-xl"
              >
                Generate Content with AI
              </motion.button>
            </>
          ) : (
            <div className="card text-center py-16">
              <FileEdit className="w-16 h-16 mx-auto text-slate-600 mb-4" />
              <h3 className="text-xl font-semibold text-white mb-2">No Report Selected</h3>
              <p className="text-slate-400">Select a report from the list or create a new one</p>
            </div>
          )}
        </div>

        {/* Outline & References */}
        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="lg:col-span-1 space-y-6"
        >
          {/* Outline */}
          <div className="card">
            <h3 className="text-lg font-semibold text-white mb-4">Outline</h3>
            {activeReport ? (
              <div className="space-y-2">
                {activeReport.outline.sections.map((section, index) => (
                  <button
                    key={section.id}
                    onClick={() => setActiveSection(section.id)}
                    className={`w-full flex items-center gap-2 p-3 rounded-lg transition-colors text-left ${
                      activeSection === section.id
                        ? 'bg-cyan-500/20 text-cyan-400'
                        : 'hover:bg-slate-700/50 text-slate-300'
                    }`}
                  >
                    <span className="text-xs text-slate-500 w-6">{index + 1}</span>
                    <span className="flex-1 text-sm">{section.title}</span>
                    <ChevronRight className="w-4 h-4" />
                  </button>
                ))}
              </div>
            ) : (
              <p className="text-slate-400 text-sm text-center py-4">Select a report</p>
            )}
          </div>

          {/* References */}
          <div className="card">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-white">References</h3>
              <button className="p-1 rounded hover:bg-slate-700 text-slate-400 hover:text-white">
                <Plus className="w-4 h-4" />
              </button>
            </div>
            <div className="space-y-3">
              {activeReport?.content.references.length === 0 ? (
                <p className="text-slate-400 text-sm text-center py-4">No references</p>
              ) : (
                activeReport?.content.references.map((ref) => (
                  <div key={ref.id} className="p-3 bg-slate-700/30 rounded-lg">
                    <p className="text-sm text-white">{ref.authors.join(', ')}</p>
                    <p className="text-xs text-slate-400 italic mt-1">{ref.title}</p>
                    <p className="text-xs text-slate-500 mt-1">
                      {ref.source}, {ref.year}
                    </p>
                  </div>
                ))
              )}
            </div>
          </div>

          {/* Stats */}
          <div className="card">
            <h3 className="text-lg font-semibold text-white mb-4">Statistics</h3>
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <span className="text-slate-400">Words</span>
                <span className="text-white font-semibold">
                  {activeReport?.wordCount.toLocaleString() || 0}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">Characters</span>
                <span className="text-white font-semibold">
                  {(activeReport?.wordCount || 0) * 5}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">Sections</span>
                <span className="text-white font-semibold">
                  {activeReport?.outline.sections.length || 0}
                </span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-slate-400">References</span>
                <span className="text-white font-semibold">
                  {activeReport?.content.references.length || 0}
                </span>
              </div>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default ReportWriter;
